ALTER TABLE events
  ADD COLUMN IF NOT EXISTS ageinvita    VARCHAR(50);

ALTER TABLE events
  ADD COLUMN IF NOT EXISTS duration_hours DOUBLE PRECISION;

ALTER TABLE events
  ADD COLUMN IF NOT EXISTS climate_type  VARCHAR(50);